### ISSUE TITLE
Описать требования по сборке

### ISSUE THREAD

**Issue by Ndochp** [ValentinKozlov/1C_PrometheusExporter#2]
К сожалению, "в лоб" не собирается с ошибкой
"Загрузка не должна менять принадлежность основного объекта конфигурации"

1С:Предприятие 8.3 (8.3.21.1274)

**Comment by Ndochp** [comment]
При более детальном рассмотрении исходников начинает казаться, что там не расширение а сама БСП, как то модули выглядят не захваченными а полными.

**Comment by ValentinKozlov** [comment]
Приветствую.
Спасибо, что нашли баг. Действительно выгрузил основную конфу БСП вместо расширения.
Исправил. Проверил, что все загружается.
